Repository dmwm/CRABServer, pull requests merged in 2019-03, with the labels that each got.

#5839 remove reuse session for FTS bug
  scripts/task_process/transfers.py
Labels: Priority: Critical, Priority: High

#5840 Resolve #5827
  scripts/cmscp.py
  src/python/TaskWorker/Actions/DagmanResubmitter.py
  src/python/TaskWorker/Actions/DagmanSubmitter.py
  src/python/TaskWorker/Actions/Splitter.py
Labels: Priority: Critical, Status: In Progress, Type: Bug

#5828 Set coherent timeouts and add FTS job metadata
  scripts/task_process/transfers.py
  src/python/TaskWorker/Actions/PostJob.py
Labels: Area: StandalonePublish/ASOless, Priority: Medium
