Repository dmwm/CRABServer, pull requests merged in 2019-08, with the labels that each got.

#5928 Resolve #5918
  src/python/TaskWorker/Actions/PostJob.py
Labels: Priority: High, Status: Done, Type: Bug

#5931 Add support comments for dmwm#5918
  src/python/TaskWorker/Actions/DagmanCreator.py
Labels: Priority: Low, Status: Done, Type: Documentation

#5935 Scriptexestdout fix 5934
  scripts/CMSRunAnalysis.py
Labels: Status: On Hold
