Repository dmwm/CRABServer, pull requests merged in 2021-07, with the labels that each got.

#6688 Use fts3 easy client and check xfers in active jobs
  scripts/task_process/FTS_Transfers.py
Labels: To be tested

#6698 add option to use gocurl for s3 operations (fix #6685)
  src/python/ServerUtilities.py
Labels: Priority: Medium, Status: In Progress, To be tested, Type: Enhancement

#6701 take SCRAM_ARCHITECTURE from jenkins (fix #6680)
  test/container/testingScripts/setupCRABClient.sh
Labels: CI/CD
